In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn as sk

In [12]:
df = pd.read_csv(r'breast_cancer.csv')
df = df.iloc[:,:-1]
df.head()
df.shape

(569, 32)

In [13]:
x = df.iloc[:, 2:].values
y = df.diagnosis.values
print(x[:2])
print(y[:5])

[[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01 2.776e-01 3.001e-01
  1.471e-01 2.419e-01 7.871e-02 1.095e+00 9.053e-01 8.589e+00 1.534e+02
  6.399e-03 4.904e-02 5.373e-02 1.587e-02 3.003e-02 6.193e-03 2.538e+01
  1.733e+01 1.846e+02 2.019e+03 1.622e-01 6.656e-01 7.119e-01 2.654e-01
  4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 1.326e+03 8.474e-02 7.864e-02 8.690e-02
  7.017e-02 1.812e-01 5.667e-02 5.435e-01 7.339e-01 3.398e+00 7.408e+01
  5.225e-03 1.308e-02 1.860e-02 1.340e-02 1.389e-02 3.532e-03 2.499e+01
  2.341e+01 1.588e+02 1.956e+03 1.238e-01 1.866e-01 2.416e-01 1.860e-01
  2.750e-01 8.902e-02]]
['M' 'M' 'M' 'M' 'M']


In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size =
0.2,random_state=500)
x_train.shape
x_test.shape
y_train.shape
y_test.shape
(y_train == 'M').sum()
(y_train=='B').sum()

278

In [17]:
278/len(y_train)
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report
baseline_pred=["B"] *len(y_train)
accuracy_score(y_train,baseline_pred) # takes actual and predicted as 2 arguments
confusion_matrix(y_train,baseline_pred)# takes actual and predicted as 2 arguments
from sklearn.naive_bayes import GaussianNB
nb_model=GaussianNB()
nb_model.fit(x_train,y_train)
print(x_train)
nb_model.score(x_train,y_train)
nb_model.score(x_test,y_test)

[[1.959e+01 1.815e+01 1.307e+02 ... 2.247e-01 3.643e-01 9.223e-02]
 [1.132e+01 2.708e+01 7.176e+01 ... 2.083e-02 2.849e-01 7.087e-02]
 [9.173e+00 1.386e+01 5.920e+01 ... 5.087e-02 3.282e-01 8.490e-02]
 ...
 [1.481e+01 1.470e+01 9.466e+01 ... 7.955e-02 2.334e-01 6.142e-02]
 [1.289e+01 1.312e+01 8.189e+01 ... 5.366e-02 2.309e-01 6.915e-02]
 [9.742e+00 1.567e+01 6.150e+01 ... 5.159e-02 2.841e-01 8.175e-02]]


0.9736842105263158

In [18]:
confusion_matrix(y_train,nb_model.predict(x_train))

array([[269,   9],
       [ 22, 155]], dtype=int64)

In [19]:
print(classification_report(y_train,nb_model.predict(x_train)))

              precision    recall  f1-score   support

           B       0.92      0.97      0.95       278
           M       0.95      0.88      0.91       177

    accuracy                           0.93       455
   macro avg       0.93      0.92      0.93       455
weighted avg       0.93      0.93      0.93       455



In [20]:
print(classification_report(y_test,nb_model.predict(x_test)))

              precision    recall  f1-score   support

           B       0.97      0.99      0.98        79
           M       0.97      0.94      0.96        35

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114

